version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mssql+pyodbc://sa:YourStrong!Passw0rd@db/recipeAPI?driver=ODBC+Driver+17+for+SQL+Server"
    depends_on:
      - db
    network_mode: "host"

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata:
